---
title: "Research Disemination Conference"

subtitle: "Case fatality ratios"

author: |
  | Peter MacPherson
  |
  | Liverpool School of Tropical Medicine, Liverpool, UK
  | Malawi-Liverpool-Wellcome Clinical Research Programme, Blantyre, Malawi
  |

date: | 
  | `r format(Sys.time(), "%B %d, %Y")`
  |
  | Table of Contents:
output: 
  html_document:
    theme: cosmo
    highlight: espresso
    toc: true
---

<br>

## 1. Backgound


<br>

## 2. Set-up

Load all required packages for analysis.

```{r setup, echo=FALSE, include=FALSE, message=FALSE, comment=NA, warning=FALSE}
library(tidyverse)    #for data manipulation
library(pmthemes)     #for ggplot themes
library(knitr)        #for tables
library(here)

```

<br>

## 3. Import datasets

Import data required for the analysis.

```{r import}
who_tb <- read_csv(here::here("data-raw/TB_burden_countries_2019-10-29.csv"))

```

<br>

## 4. Tidying and recoding

```{r tidy}
cfr_whotb <- who_tb %>%
              select(country,g_whoregion,year,contains("cfr")) %>%
              filter(!is.na(cfr)) %>%
              arrange(-cfr) %>%
              slice(1:20)

cfr_whotb <- cfr_whotb %>%
              mutate( who_region = case_when(
                g_whoregion == "EUR" ~ "Europe",
                g_whoregion == "AFR" ~ "Africa",
                g_whoregion == "EMR" ~ "Eastern Mediterranean",
                g_whoregion == "AMR" ~ "Region of America",
              ))

use_data(cfr_whotb, overwrite = TRUE)
```


<br>

## X. Reproducibility

This reproduction of the analysis was run by: 

```{r sysinfo, echo=FALSE, message=FALSE, comment=NA, warning=FALSE}

sysinfo <- Sys.info()

sysinfo <- data.frame(keyName=names(sysinfo), value=sysinfo, row.names=NULL)

sysinfo %>% kable()
```

Analysis was run at **`r Sys.time()`**, and using the following Session Info:

```{r sessioninfo, echo=FALSE, results='markdown', message=FALSE, comment=NA, warning=FALSE}
sessionInfo()
```
